////////////////////////////////////////////////////////////////////////////////
//
// Copyright  Â© 2013 E-Learning Research Lab, 
// Amrita Vishwa Vidyapeetham. All rights reserved. 
// E-Learning Research Lab and the A-VIEW logo are trademarks or
// registered trademarks of E-Learning Research Lab. 
// All other names used are the trademarks of their respective owners.
//
////////////////////////////////////////////////////////////////////////////////

/**
 *
 * File			: UserActionVO.as
 * Module		: Audit
 * Developer(s)	: Ramesh G, Sethu, Ashish
 * Reviewer(s)	: Meena S
 *
 * Value Object Class for Users Action, user_action table.
 * Holds the action details for each action made by the user
 *
 */

package edu.amrita.aview.audit.vo
{
	import edu.amrita.aview.common.vo.Auditable;
	
	[RemoteClass(alias="edu.amrita.aview.audit.entities.UserAction")]
	
	/**
	 * Value Object Class for Users Action, user_action table.
	 * Holds the action details for each action made by the user
	 *
	 */
	public class UserActionVO extends Auditable
	{
		/**
		 * @Constructor
		 * Default, no argument constructor. No business logic here. 
		 * 
		 */
		public function UserActionVO()
		{
		}
		
		/**
		 * Primary key, auto generated by database, while inserting a new user action.
		 */
		private var _userActionId:int;
		
		/**
		 * Refrence to the login entry audit id
		 */
		private var _auditUserLoginId:int;
		
		/**
		 * Primary Key, Id of the Action being audited
		 */
		private var _actionId:int;
		
		/**
		 * First associated details related to the action
		 */
		private var _attribute1Value:String;
		
		/**
		 * Second associated details related to the action
		 */
		private var _attribute2Value:String;
		
		/**
		 * Third associated details related to the action
		 */
		private var _attribute3Value:String;
		
		/**
		 * Server time when the action occured. This variable is populated on the server up on reciept of the action
		 */
		private var _actionTimeMS:Number;
		
		/**
		 * Reference to the lecture id
		 */
		private var _lectureId:Number=0;
		
		/**
		 * Refrence to the login entry audit id
		 */
		private var _auditLectureId:Number=0;
		
		/**
		 *
		 * @public
		 * Gets the userActionId
		 * Primary key, auto generated by database, while inserting a new user action.
		 *
		 *
		 * @return int
		 */
		public function get userActionId():int
		{
			return _userActionId;
		}
		
		/**
		 *
		 * @public
		 * Sets the userActionId
		 * Primary key, auto generated by database, while inserting a new user action.
		 *
		 * @param userActionId type of int
		 * @return void
		 */
		public function set userActionId(userActionId:int):void
		{
			this._userActionId=userActionId;
		}
		
		/**
		 *
		 * @public
		 * Gets the auditUserLoginId
		 * Refrence to the login entry audit id
		 *
		 *
		 * @return int
		 */
		public function get auditUserLoginId():int
		{
			return _auditUserLoginId;
		}
		
		/**
		 *
		 * @public
		 * Sets the auditUserLoginId
		 * Refrence to the login entry audit id
		 *
		 * @param auditUserLoginId type of int
		 * @return void
		 */
		public function set auditUserLoginId(auditUserLoginId:int):void
		{
			
			this._auditUserLoginId=auditUserLoginId;
		}
		
		/**
		 *
		 * @public
		 * Gets the actionId
		 * Primary Key, Id of the Action being audited
		 *
		 *
		 * @return int
		 */
		public function get actionId():int
		{
			return _actionId;
		}
		
		/**
		 *
		 * @public
		 * Sets the actionId
		 * Primary Key, Id of the Action being audited
		 *
		 * @param actionId type of int
		 * @return void
		 */
		public function set actionId(actionId:int):void
		{
			this._actionId=actionId;
		}
		
		/**
		 *
		 * @public
		 * Gets the attribute1Value
		 * First associated details related to the action
		 *
		 *
		 * @return String
		 */
		public function get attribute1Value():String
		{
			return _attribute1Value;
		}
		
		/**
		 *
		 * @public
		 * Sets the attribute1Value
		 * First associated details related to the action
		 *
		 * @param value type of String
		 * @return void
		 */
		public function set attribute1Value(value:String):void
		{
			_attribute1Value=value;
		}
		
		/**
		 *
		 * @public
		 * Gets the attribute2Value
		 * Second associated details related to the action
		 *
		 *
		 * @return String
		 */
		public function get attribute2Value():String
		{
			return _attribute2Value;
		}
		
		/**
		 *
		 * @public
		 * Sets the attribute2Value
		 * Second associated details related to the action
		 *
		 * @param value type of String
		 * @return void
		 */
		public function set attribute2Value(value:String):void
		{
			_attribute2Value=value;
		}
		
		/**
		 *
		 * @public
		 * Gets the attribute3Value
		 * Third associated details related to the action
		 *
		 *
		 * @return String
		 */
		public function get attribute3Value():String
		{
			return _attribute3Value;
		}
		
		/**
		 *
		 * @public
		 * Sets the attribute3Value
		 * Third associated details related to the action
		 *
		 * @param value type of String
		 * @return void
		 */
		public function set attribute3Value(value:String):void
		{
			_attribute3Value=value;
		}
		
		/**
		 *
		 * @public
		 * Gets the actionTimeMS
		 * Server time when the action occured. This variable is populated on the server up on reciept of the action
		 *
		 *
		 * @return Number
		 */
		public function get actionTimeMS():Number
		{
			return _actionTimeMS;
		}
		
		/**
		 *
		 * @public
		 * Sets the actionTimeMS
		 * Server time when the action occured. This variable is populated on the server up on reciept of the action
		 *
		 * @param value type of Number
		 * @return void
		 */
		public function set actionTimeMS(value:Number):void
		{
			_actionTimeMS=value;
		}
		
		/**
		 *
		 * @public
		 * Gets the lectureId
		 * Reference to the lecture id
		 *
		 *
		 * @return Number
		 */
		public function get lectureId():Number
		{
			return _lectureId;
		}
		
		/**
		 *
		 * @public
		 * Sets the lectureId
		 * Reference to the lecture id
		 *
		 * @param value type of Number
		 * @return void
		 */
		public function set lectureId(value:Number):void
		{
			_lectureId=value;
		}
		
		/**
		 *
		 * @public
		 * Gets the auditLectureId
		 * Refrence to the login entry audit id
		 *
		 *
		 * @return Number
		 */
		public function get auditLectureId():Number
		{
			return _auditLectureId;
		}
		
		/**
		 *
		 * @public
		 * Sets the auditLectureId
		 * Refrence to the login entry audit id
		 *
		 * @param value type of Number
		 * @return void
		 */
		public function set auditLectureId(value:Number):void
		{
			_auditLectureId=value;
		}
	
	}
}
