////////////////////////////////////////////////////////////////////////////////
//
// Copyright  © 2013 E-Learning Research Lab, 
// Amrita Vishwa Vidyapeetham. All rights reserved. 
// E-Learning Research Lab and the A-VIEW logo are trademarks or
// registered trademarks of E-Learning Research Lab. 
// All other names used are the trademarks of their respective owners.
//
////////////////////////////////////////////////////////////////////////////////

/**
 *
 *
 * File			: GroupVO.as
 * Module		: contacts
 * Developer(s)	: NidhiSarasan,Soumya M.D
 * Reviewer(s)	: Veena Gopal K.V
 *
 *
 *
 */
/**
 * package for Group.
 */
//VGCR:-Function Description
package edu.amrita.aview.contacts.vo
{
	import edu.amrita.aview.common.vo.Auditable;
	
	import mx.collections.ArrayCollection;
	
	[RemoteClass(alias="edu.amrita.aview.contacts.entities.ContactGroup")]
	
	/**
	 * @public
	 * //PNCR: description
	 * extends Auditable
	 * 
	 */
	public dynamic class GroupVO extends Auditable
	{
		
		/**
		 * @public
		 * constructor
		 */
		public function GroupVO()
		{
		
		}
		/**
		 * Primary key, auto generated by database, while inserting a group.
		 */
		private var _contactGroupId:Number=01;
		/**
		 * Group name
		 */
		private var _contactgroupName:String=null;
		/**
		 * Id of groupOwner
		 */
		private var _groupOwnerId:Number=0;
		
		/**
		 * count of group members 
		 */
		private var _memberCount:Number=0;
		
		/**
		 * list of group users 
		 */
		private var _groupUsers:ArrayCollection = null;
		
		//The following booleans are added for GUI (People.mxml & CreateRoom.mxml) purposes
		private var _isExisting:Boolean = false;
		private var _isSelected:Boolean = false;
		private var _isSelectable:Boolean = false;
		private var _isExpanded:Boolean = false;
		
		/**
		 * @public
		 * get function for group owner id
		 * @return Number
		 */
		public function get groupOwnerId():Number
		{
			return _groupOwnerId;
		}
		
		/**
		 * @public
		 * set function for group owner id
		 * @param value of type Number
		 */
		public function set groupOwnerId(value:Number):void
		{
			_groupOwnerId=value;
		}
		
		/**
		 * @public
		 * function to get contact group name
		 * @return String
		 */
		public function get contactGroupName():String
		{
			return _contactgroupName;
		}
		
		/**
		 * @public
		 * function to set contact group name
		 * @param value of type String
		 */
		public function set contactGroupName(value:String):void
		{
			_contactgroupName=value;
		}
		
		/**
		 * @public
		 * function to get contact group id
		 * @return Number
		 *
		 */
		public function get contactGroupId():Number
		{
			return _contactGroupId;
		}
		
		/**
		 * @public
		 * function to set contact group id
		 * @param value of type Number
		 * 
		 */
		public function set contactGroupId(value:Number):void
		{
			_contactGroupId=value;
		}
		
		
		/**
		 * @public
		 * @return 
		 * count of group members
		 */
		public function get memberCount():Number
		{
			return _memberCount;
		}
		
		public function set memberCount(value:Number):void
		{
			_memberCount = value;
		}
		
		public function get groupUsers():ArrayCollection
		{
			return _groupUsers;
		}
		
		public function set groupUsers(value:ArrayCollection):void
		{
			_groupUsers = value;
			if(groupUsers!=null)
			{
				_memberCount=_groupUsers.length;
			}
			else
			{
				_memberCount=0;
			}
		}
		
		public function get isExisting():Boolean
		{
			return _isExisting;
		}
		
		public function set isExisting(value:Boolean):void
		{
			_isExisting = value;
		}
		
		public function get isSelected():Boolean
		{
			return _isSelected;
		}
		
		public function set isSelected(value:Boolean):void
		{
			_isSelected = value;
		}
		
		public function get isSelectable():Boolean
		{
			return _isSelectable;
		}
		
		public function set isSelectable(value:Boolean):void
		{
			_isSelectable = value;
		}
		
		public function get isExpanded():Boolean
		{
			return _isExpanded;
		}
		
		public function set isExpanded(value:Boolean):void
		{
			_isExpanded=value;
		}
		public function get contactName():String
		{
			return _contactgroupName;
		}
	
	}
}
