package edu.amrita.aview.contacts.vo
{
	import edu.amrita.aview.core.gclm.vo.UserVO;
	import edu.amrita.aview.core.shared.vo.Auditable;
	
	[RemoteClass(alias="edu.amrita.aview.contacts.entities.GroupTransfer")]
	public class GroupTransferVO extends Auditable
	{
		private var _groupTransferId:Number=01;
		private var _group:GroupVO=null;
		private var _receiver:UserVO=null;
		private var _sender:UserVO=null;
		public function GroupTransferVO()
		{
			super();
		}
		
		/**
		 * Primary key, auto generated by database, while inserting group tranfer entry.
		 */
		public function get groupTransferId():Number
		{
			return _groupTransferId;
		}

		/**
		 * @public
		 */
		public function set groupTransferId(value:Number):void
		{
			_groupTransferId = value;
		}

		/**
		 * Group  details
		 */
		public function get group():GroupVO
		{
			return _group;
		}

		/**
		 * @public
		 */
		public function set group(value:GroupVO):void
		{
			_group = value;
		}

		/**
		 * receiver Details
		 */
		public function get receiver():UserVO
		{
			return _receiver;
		}

		/**
		 * @public
		 */
		public function set receiver(value:UserVO):void
		{
			_receiver = value;
		}
		
		
		public function get sender():UserVO
		{
			return _sender;
		}

		public function set sender(value:UserVO):void
		{
			_sender = value;
		}

		public function get contactGroupName():String
		{
			return _group.contactGroupName;
		}

	}
}