////////////////////////////////////////////////////////////////////////////////
//
// Copyright  © 2013 E-Learning Research Lab, 
// Amrita Vishwa Vidyapeetham. All rights reserved. 
// E-Learning Research Lab and the A-VIEW logo are trademarks or
// registered trademarks of E-Learning Research Lab. 
// All other names used are the trademarks of their respective owners.
//
////////////////////////////////////////////////////////////////////////////////

/**
 *
 * File			: ActionVO.as
 * Module		: Audit
 * Developer(s)	: Ramesh G, Sethu, Ashish
 * Reviewer(s)	: Meena S
 *
 * Value Object Class for Action, action table
 * Holds the action specification such as Action name
 * and associated details collected along with it.
 *
 */
package edu.amrita.aview.core.shared.audit.vo
{
	import edu.amrita.aview.core.shared.vo.Auditable;
	
	[RemoteClass(alias="edu.amrita.aview.audit.entities.Action")]
	
	/**
	 * Value Object Class for Action, action table
	 * Holds the action specification such as Action name
	 * and associated details collected along with it.
	 */
	public class ActionVO extends Auditable
	{
		/**
		 *
		 * @public
		 * constructor
		 */
		public function ActionVO()
		{
		}
		
		/**
		 * Primary key, auto generated by database, while inserting a new action.
		 */
		private var _actionId:int=0;
		
		/**
		 * Action name
		 */
		private var _actionName:String=null;
		
		/**
		 * Name of the 1st Attribute, a detail associated with the action.
		 */
		private var _attribute1Name:String=null;
		
		/**
		 * Name of the 2nd Attribute, a detail associated with the action.
		 */
		private var _attribute2Name:String=null;
		
		/**
		 * Name of the 3rd Attribute, a detail associated with the action.
		 */
		private var _attribute3Name:String=null;
		
		/**
		 *
		 * @public
		 * Gets the action Id
		 *
		 *
		 * @return int
		 */
		public function get actionId():int
		{
			return _actionId;
		}
		
		/**
		 *
		 * @public
		 * Sets the action id
		 *
		 * @param actionId type of int
		 * @return void
		 */
		public function set actionId(actionId:int):void
		{
			this._actionId=actionId;
		}
		
		/**
		 *
		 * @public
		 * Gets the action name
		 *
		 *
		 * @return String
		 */
		public function get actionName():String
		{
			return _actionName;
		}
		
		/**
		 *
		 * @public
		 * Sets the action name
		 *
		 * @param actionName type of String
		 * @return void
		 */
		public function set actionName(actionName:String):void
		{
			this._actionName=actionName;
		}
		
		/**
		 *
		 * @public
		 * Gets the 1st Attribute Name
		 *
		 *
		 * @return String
		 */
		public function get attribute1Name():String
		{
			return _attribute1Name;
		}
		
		/**
		 *
		 * @public
		 * Sets the 1st Attribute Name
		 *
		 * @param value type of String
		 * @return void
		 */
		public function set attribute1Name(value:String):void
		{
			_attribute1Name=value;
		}
		
		/**
		 *
		 * @public
		 * Gets the 2nd Attribute Name
		 *
		 *
		 * @return String
		 */
		public function get attribute2Name():String
		{
			return _attribute2Name;
		}
		
		/**
		 *
		 * @public
		 * Sets the 2nd Attribute Name
		 *
		 * @param value type of String
		 * @return void
		 */
		public function set attribute2Name(value:String):void
		{
			_attribute2Name=value;
		}
		
		/**
		 *
		 * @public
		 * Gets the 3rd Attribute Name
		 *
		 *
		 * @return String
		 */
		public function get attribute3Name():String
		{
			return _attribute3Name;
		}
		
		/**
		 *
		 * @public
		 * Sets the 3rd Attribute Name
		 *
		 * @param value type of String
		 * @return void
		 */
		public function set attribute3Name(value:String):void
		{
			_attribute3Name=value;
		}
	
	
	}
}
